site_name: Simple backuper documentation
nav:
  - Introduction: index.md
  - About the project: about.md
  - English:
    - Overview: eng/indexeng.md
    - Doc for developers: eng/projectForBeg/docfordev.md  # <- Исправил порядок и убрал лишние отступы
    - Doc for beginners: eng/projectForDev/docforbeg.md
  - Russian:
    - Обзор: ru/indexru.md
    - Дока для разработчиков: ru/docfordevru.md
    - Дока для начинающих: ru/docforbegru.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
  palette:
    primary: blue
    accent: light blue
